version: "3"
services:
  app:
    image: "app"
    build:
      context: ./CS554FinalProject/
    container_name: app
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - messager
    links:
      - messager

  messager:
    image: "messager"
    build:
      context: ./messager/
    container_name: messager
    expose:
      - 8080
    ports:
      - 8080:8080
